services:
  xdmod:
    build: .
    image: xdmod
    container_name: xdmod-container
    hostname: xdmod.tcluster01.msu270
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      # Данные MySQL
      - mysql_data:/var/lib/mysql
      # Конфигурации XDMoD
      - xdmod_config:/etc/xdmod
      - xdmod_etc:/usr/share/xdmod/etc
      # Логи XDMoD
      - xdmod_logs:/var/log/xdmod
      # SLURM данные с хоста
      - /var/log/slurm:/var/log/slurm:ro
      - /var/spool/slurm:/var/spool/slurm:ro
      - /opt/slurm:/opt/slurm:ro
      - /etc/slurm:/etc/slurm:ro
      - /var/run/munge:/var/run/munge:ro
      # Директория для экспорта данных
      - /opt/xdmod-data:/opt/xdmod-data
    environment:
      - MYSQL_ROOT_PASSWORD=secure_root_password_123
      - XDMOD_DB_PASSWORD=secure_xdmod_password_123
      - TZ=UTC
    restart: unless-stopped
    networks:
      - xdmod-network

networks:
  xdmod-network:
    name: xdmod-network

volumes:
  mysql_data:
  xdmod_config:
  xdmod_etc:
  xdmod_logs: